INFO 2021-01-15 07:33:47,431 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 07:38:58,248 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 07:46:53,208 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 07:48:11,166 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-15 07:48:13,760 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 07:48:39,294 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 07:48:39,298 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 1989
WARNING 2021-01-15 07:49:32,469 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 07:49:32,473 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 1989
WARNING 2021-01-15 07:49:59,128 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 07:49:59,132 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 1989
WARNING 2021-01-15 07:51:41,961 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 07:51:41,964 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 1989
INFO 2021-01-15 08:20:10,100 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 08:20:27,860 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 08:20:27,861 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2194
WARNING 2021-01-15 08:20:30,250 log 222 Not Found: /image_codes/22fd3d8b-1fb7-41c0-a3f9-ce9f395d0ae5/
WARNING 2021-01-15 08:20:30,251 basehttp 154 "GET /image_codes/22fd3d8b-1fb7-41c0-a3f9-ce9f395d0ae5/ HTTP/1.1" 404 2302
INFO 2021-01-15 08:20:55,862 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:21:25,824 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:22:13,594 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:22:26,878 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:22:30,120 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:23:21,617 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-15 08:23:24,123 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:23:37,410 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-15 08:23:39,616 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:23:45,191 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:23:48,290 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
WARNING 2021-01-15 08:23:51,737 log 222 Not Found: /image_codes/c8fa6565-31f5-44db-8077-bbdb6c36d6c5/
WARNING 2021-01-15 08:23:51,738 basehttp 154 "GET /image_codes/c8fa6565-31f5-44db-8077-bbdb6c36d6c5/ HTTP/1.1" 404 2302
INFO 2021-01-15 08:24:03,992 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:24:32,067 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 08:24:35,892 log 222 Not Found: /image_codes/edb07024-7b5e-4108-9007-3574b559c38f/
WARNING 2021-01-15 08:24:35,893 basehttp 154 "GET /image_codes/edb07024-7b5e-4108-9007-3574b559c38f/ HTTP/1.1" 404 2302
INFO 2021-01-15 08:24:41,102 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:26:39,924 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2021-01-15 08:26:42,326 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:28:17,891 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 08:28:20,596 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:29:01,175 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 08:29:07,095 log 222 Not Found: /image_codes/5da3127f-f98f-4f1f-8e84-da9b9bde3dfd/
WARNING 2021-01-15 08:29:07,096 basehttp 154 "GET /image_codes/5da3127f-f98f-4f1f-8e84-da9b9bde3dfd/ HTTP/1.1" 404 2485
INFO 2021-01-15 08:29:08,815 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:29:11,339 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:29:15,574 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:30:07,626 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 08:30:10,722 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:35:56,721 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-15 08:36:03,698 log 222 Internal Server Error: /image_codes/d8a40786-b56d-4521-800d-ad1bacff67dc/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    conn = get_redis_connection('verify_code')
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/cache/__init__.py", line 75, in __getitem__
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES
ERROR 2021-01-15 08:36:03,708 basehttp 154 "GET /image_codes/d8a40786-b56d-4521-800d-ad1bacff67dc/ HTTP/1.1" 500 89538
ERROR 2021-01-15 08:36:05,846 log 222 Internal Server Error: /image_codes/e0cf79ec-818e-49e4-ae02-5c39d71ff263/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    conn = get_redis_connection('verify_code')
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/cache/__init__.py", line 75, in __getitem__
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES
ERROR 2021-01-15 08:36:05,847 basehttp 154 "GET /image_codes/e0cf79ec-818e-49e4-ae02-5c39d71ff263/ HTTP/1.1" 500 89552
ERROR 2021-01-15 08:36:06,725 log 222 Internal Server Error: /image_codes/00a30805-c8a5-43da-b62f-72c54c3c1506/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    conn = get_redis_connection('verify_code')
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/cache/__init__.py", line 75, in __getitem__
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES
ERROR 2021-01-15 08:36:06,727 basehttp 154 "GET /image_codes/00a30805-c8a5-43da-b62f-72c54c3c1506/ HTTP/1.1" 500 89536
ERROR 2021-01-15 08:36:07,242 log 222 Internal Server Error: /image_codes/35f9c875-c903-4639-8674-42035b1f0ef6/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    conn = get_redis_connection('verify_code')
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/cache/__init__.py", line 75, in __getitem__
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES
ERROR 2021-01-15 08:36:07,249 basehttp 154 "GET /image_codes/35f9c875-c903-4639-8674-42035b1f0ef6/ HTTP/1.1" 500 89544
ERROR 2021-01-15 08:36:07,355 log 222 Internal Server Error: /image_codes/cf8c4605-b3d7-41e6-abed-b67d9722e3b4/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 22, in get
    conn = get_redis_connection('verify_code')
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/cache/__init__.py", line 75, in __getitem__
    raise InvalidCacheBackendError(
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES
ERROR 2021-01-15 08:36:07,356 basehttp 154 "GET /image_codes/cf8c4605-b3d7-41e6-abed-b67d9722e3b4/ HTTP/1.1" 500 89534
INFO 2021-01-15 08:39:29,194 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:39:48,695 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:39:55,396 basehttp 154 "GET /image_codes/aceef2f0-7cea-4b04-903c-3c63fec5a31c/ HTTP/1.1" 200 3261
INFO 2021-01-15 08:39:56,783 basehttp 154 "GET /image_codes/9db3c94f-61f6-461a-9cd8-47917a753f0a/ HTTP/1.1" 200 3002
INFO 2021-01-15 08:39:57,174 basehttp 154 "GET /image_codes/a369f2e0-a6c8-4240-bc64-53859b8375a7/ HTTP/1.1" 200 3528
INFO 2021-01-15 08:39:57,317 basehttp 154 "GET /image_codes/2dbf57ec-ab9e-437f-ba0e-d461807438ca/ HTTP/1.1" 200 3601
INFO 2021-01-15 08:39:57,462 basehttp 154 "GET /image_codes/a108b59c-26d5-4a74-bdb4-1bc8d7139012/ HTTP/1.1" 200 3332
INFO 2021-01-15 08:39:57,610 basehttp 154 "GET /image_codes/6115c54b-5961-48f9-ad84-1438166f4c35/ HTTP/1.1" 200 2852
INFO 2021-01-15 08:39:57,728 basehttp 154 "GET /image_codes/ce8fda41-5be5-4e40-9d6d-e181071ac219/ HTTP/1.1" 200 3566
INFO 2021-01-15 08:43:46,924 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:43:50,415 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:43:55,105 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:43:57,774 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:44:07,029 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:44:09,380 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:44:16,617 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:44:20,171 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:44:48,081 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:44:50,701 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:44:59,504 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2021-01-15 08:45:02,000 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:49:53,878 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:49:56,703 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:50:14,473 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:50:17,166 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:54:00,412 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:54:03,395 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:54:09,687 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:54:12,005 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:54:35,456 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:54:37,853 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:54:40,694 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:54:41,438 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:54:45,385 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:54:46,178 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:54:50,068 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2021-01-15 08:54:50,883 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:55:43,659 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 08:57:37,911 basehttp 154 "GET /image_codes/3f40b1fc-5400-44ed-9fad-ecb2d21b60b1/ HTTP/1.1" 200 3318
INFO 2021-01-15 08:57:40,663 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:57:47,560 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:57:50,676 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:57:51,177 basehttp 154 "GET /sms_codes/18515441598/?image_code=tnnj&image_code_id=3f40b1fc-5400-44ed-9fad-ecb2d21b60b1 HTTP/1.1" 200 27
INFO 2021-01-15 08:58:12,402 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2021-01-15 08:58:12,468 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:58:12,473 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 08:58:12,988 basehttp 154 "POST /register/ HTTP/1.1" 200 73
WARNING 2021-01-15 08:58:16,066 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 08:58:16,067 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2889
INFO 2021-01-15 09:01:05,216 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 09:01:10,014 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:01:24,905 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 09:01:27,222 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:01:44,995 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 09:01:48,247 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:01:52,125 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 09:01:52,922 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:03:53,239 basehttp 154 "GET /image_codes/06bf650d-bceb-4eb4-8c82-1bf50948a7e2/ HTTP/1.1" 200 3176
INFO 2021-01-15 09:04:01,476 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 09:04:08,513 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 09:04:12,040 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 09:04:12,607 basehttp 154 "GET /sms_codes/18515441598/?image_code=aqc9&image_code_id=06bf650d-bceb-4eb4-8c82-1bf50948a7e2 HTTP/1.1" 200 27
INFO 2021-01-15 09:04:25,954 basehttp 154 "GET /usernames/yuanchu1598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 09:04:25,961 basehttp 154 "GET /mobiles/18515441598/count/ HTTP/1.1" 200 39
INFO 2021-01-15 09:04:25,971 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2021-01-15 09:04:26,288 basehttp 154 "POST /register/ HTTP/1.1" 200 73
WARNING 2021-01-15 09:04:29,148 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:04:29,149 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2889
INFO 2021-01-15 09:26:10,902 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 09:26:19,485 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:26:19,488 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3194
WARNING 2021-01-15 09:26:24,458 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 09:26:24,459 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3206
INFO 2021-01-15 09:26:24,550 basehttp 154 "GET /info/ HTTP/1.1" 200 131
WARNING 2021-01-15 09:26:27,784 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:26:27,788 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3194
WARNING 2021-01-15 09:26:38,530 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:26:38,533 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3194
INFO 2021-01-15 09:26:48,111 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2021-01-15 09:26:48,351 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2021-01-15 09:26:54,396 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2021-01-15 09:26:54,568 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2021-01-15 09:27:04,284 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2021-01-15 09:27:04,568 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2021-01-15 09:27:06,855 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:27:06,856 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3194
INFO 2021-01-15 09:27:56,602 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:28:14,646 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2021-01-15 09:28:15,089 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2021-01-15 09:28:17,711 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:28:17,712 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3194
WARNING 2021-01-15 09:28:23,449 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 09:28:23,451 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3206
INFO 2021-01-15 09:28:23,512 basehttp 154 "GET /info/ HTTP/1.1" 200 131
WARNING 2021-01-15 09:28:29,011 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:28:29,012 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3194
INFO 2021-01-15 09:29:03,635 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 09:29:06,119 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:30:36,215 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-15 09:30:39,209 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:31:29,388 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/oauth/models.py changed, reloading.
INFO 2021-01-15 09:31:31,713 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:39:28,981 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-15 09:39:31,559 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:41:10,857 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2021-01-15 09:41:14,027 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:46:24,449 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 09:58:30,173 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 09:59:36,607 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 09:59:36,615 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3520
WARNING 2021-01-15 10:01:20,146 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:01:20,150 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3520
WARNING 2021-01-15 10:02:32,342 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:02:32,348 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3520
INFO 2021-01-15 10:02:41,545 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
WARNING 2021-01-15 10:03:34,954 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:03:34,961 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3520
WARNING 2021-01-15 10:06:06,550 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:06:06,553 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3520
WARNING 2021-01-15 10:19:19,046 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:19:19,053 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3520
INFO 2021-01-15 10:19:22,611 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
WARNING 2021-01-15 10:19:22,643 log 222 Not Found: /logout/
WARNING 2021-01-15 10:19:22,644 basehttp 154 "DELETE /logout/ HTTP/1.1" 404 3505
INFO 2021-01-15 10:20:31,916 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-01-15 10:20:35,140 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 10:22:15,238 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-15 10:22:26,712 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:22:26,719 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3674
INFO 2021-01-15 10:23:10,157 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2021-01-15 10:23:10,457 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2021-01-15 10:23:13,389 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2021-01-15 10:23:39,357 basehttp 154 "GET /oauth_callback/?code=117AD68A7FF8D87206CEEABF3ACAC02B HTTP/1.1" 200 263
INFO 2021-01-15 10:23:39,651 basehttp 154 "GET /image_codes/9a111c4f-008a-4ebb-aa17-98c37637a3af/ HTTP/1.1" 200 3183
INFO 2021-01-15 10:23:48,404 basehttp 154 "GET /image_codes/8cda3bbb-d58c-4198-9ac3-5ed3e7cdfe06/ HTTP/1.1" 200 3137
INFO 2021-01-15 10:23:51,515 basehttp 154 "GET /sms_codes/18515441598/?image_code=waks&image_code_id=8cda3bbb-d58c-4198-9ac3-5ed3e7cdfe06 HTTP/1.1" 200 27
INFO 2021-01-15 10:24:38,602 basehttp 154 "OPTIONS /oauth_callback/ HTTP/1.1" 200 0
INFO 2021-01-15 10:24:38,939 basehttp 154 "POST /oauth_callback/ HTTP/1.1" 200 27
WARNING 2021-01-15 10:24:40,590 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 10:24:40,590 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3674
WARNING 2021-01-15 10:24:47,048 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 10:24:47,050 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3686
INFO 2021-01-15 10:24:47,084 basehttp 154 "GET /info/ HTTP/1.1" 200 131
INFO 2021-01-15 11:45:37,375 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 11:46:44,018 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2021-01-15 11:46:44,415 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2021-01-15 11:46:45,980 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 11:46:45,983 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3828
WARNING 2021-01-15 11:47:06,814 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 11:47:06,816 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3840
INFO 2021-01-15 11:47:06,867 basehttp 154 "GET /info/ HTTP/1.1" 200 132
WARNING 2021-01-15 11:47:10,396 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 11:47:10,397 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3828
WARNING 2021-01-15 11:47:13,328 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 11:47:13,329 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3840
INFO 2021-01-15 11:47:13,365 basehttp 154 "GET /info/ HTTP/1.1" 200 132
INFO 2021-01-15 11:47:41,158 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2021-01-15 11:47:41,374 log 222 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py", line 286, in put
    verify_url = generate_verify_email_url(request)
NameError: name 'generate_verify_email_url' is not defined
ERROR 2021-01-15 11:47:41,376 basehttp 154 "PUT /emails/ HTTP/1.1" 500 82104
INFO 2021-01-15 11:49:07,487 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 11:49:11,066 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2021-01-15 11:49:11,709 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2021-01-15 11:49:23,250 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTYxMDcxMTM1MSwiZXhwIjoxNjEwNzE0OTUxfQ.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Inl1YW5jaHUxNTk4IiwiZW1haWwiOiJ5dWFuY2h1MTU5OEAxNjMuY29tIn0.fFLq3SwLbA4HsazTYcLR-bKZmqTCU5YP5x3HfKEwPWu9YL4AnZ29jiSSZjXwpAweobzRWV8LRAfc_flBSUmnvQ HTTP/1.1" 200 0
WARNING 2021-01-15 11:49:23,274 log 222 Not Found: /emails/verification/
WARNING 2021-01-15 11:49:23,275 basehttp 154 "PUT /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTYxMDcxMTM1MSwiZXhwIjoxNjEwNzE0OTUxfQ.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Inl1YW5jaHUxNTk4IiwiZW1haWwiOiJ5dWFuY2h1MTU5OEAxNjMuY29tIn0.fFLq3SwLbA4HsazTYcLR-bKZmqTCU5YP5x3HfKEwPWu9YL4AnZ29jiSSZjXwpAweobzRWV8LRAfc_flBSUmnvQ HTTP/1.1" 404 4101
WARNING 2021-01-15 11:49:31,273 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 11:49:31,275 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3840
INFO 2021-01-15 11:49:31,325 basehttp 154 "GET /info/ HTTP/1.1" 200 151
INFO 2021-01-15 11:50:50,638 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-15 11:50:53,192 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 11:51:12,159 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-15 11:51:20,504 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2021-01-15 11:51:21,127 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2021-01-15 11:51:29,828 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTYxMDcxMTQ4MCwiZXhwIjoxNjEwNzE1MDgwfQ.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Inl1YW5jaHUxNTk4IiwiZW1haWwiOiJ5dWFuY2h1MTU5OEAxNjMuY29tIn0.ip2to39CVsMkKJceQjJeuUlyT9jWpTwYSSSvqoWk0IYE34y7k3bAhEAHi5NDj7e5oxKyKiJSxy6eMl9kOJovtA HTTP/1.1" 200 0
INFO 2021-01-15 11:51:29,914 basehttp 154 "PUT /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTYxMDcxMTQ4MCwiZXhwIjoxNjEwNzE1MDgwfQ.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Inl1YW5jaHUxNTk4IiwiZW1haWwiOiJ5dWFuY2h1MTU5OEAxNjMuY29tIn0.ip2to39CVsMkKJceQjJeuUlyT9jWpTwYSSSvqoWk0IYE34y7k3bAhEAHi5NDj7e5oxKyKiJSxy6eMl9kOJovtA HTTP/1.1" 200 27
WARNING 2021-01-15 11:51:32,330 log 222 Not Found: /carts/simple/
WARNING 2021-01-15 11:51:32,332 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3995
WARNING 2021-01-15 11:52:42,950 log 222 Not Found: /browse_histories/
WARNING 2021-01-15 11:52:42,955 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4007
INFO 2021-01-15 11:52:42,990 basehttp 154 "GET /info/ HTTP/1.1" 200 150
INFO 2021-01-16 02:30:19,929 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 02:30:42,595 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:30:42,600 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4151
WARNING 2021-01-16 02:30:50,622 log 222 Not Found: /browse_histories/
WARNING 2021-01-16 02:30:50,623 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4163
INFO 2021-01-16 02:30:50,693 basehttp 154 "GET /info/ HTTP/1.1" 200 150
WARNING 2021-01-16 02:30:54,370 log 222 Not Found: /addresses/
WARNING 2021-01-16 02:30:54,375 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4142
WARNING 2021-01-16 02:30:54,380 log 222 Not Found: /areas/
WARNING 2021-01-16 02:30:54,382 basehttp 154 "GET /areas/ HTTP/1.1" 404 4130
INFO 2021-01-16 02:31:50,548 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/urls.py changed, reloading.
INFO 2021-01-16 02:31:55,389 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 02:32:01,357 log 222 Not Found: /browse_histories/
WARNING 2021-01-16 02:32:01,358 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4484
INFO 2021-01-16 02:32:01,396 basehttp 154 "GET /info/ HTTP/1.1" 200 150
WARNING 2021-01-16 02:32:03,397 log 222 Not Found: /addresses/
WARNING 2021-01-16 02:32:03,398 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4463
INFO 2021-01-16 02:32:03,481 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2021-01-16 02:32:13,890 basehttp 154 "GET /areas/120000/ HTTP/1.1" 200 141
INFO 2021-01-16 02:32:15,385 basehttp 154 "GET /areas/120100/ HTTP/1.1" 200 837
INFO 2021-01-16 02:32:26,101 basehttp 154 "OPTIONS /addresses/create/ HTTP/1.1" 200 0
WARNING 2021-01-16 02:32:26,115 log 222 Not Found: /addresses/create/
WARNING 2021-01-16 02:32:26,115 basehttp 154 "POST /addresses/create/ HTTP/1.1" 404 4485
WARNING 2021-01-16 02:32:34,921 log 222 Not Found: /addresses/create/
WARNING 2021-01-16 02:32:34,924 basehttp 154 "POST /addresses/create/ HTTP/1.1" 404 4485
INFO 2021-01-16 02:33:20,889 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2021-01-16 02:33:23,621 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:35:01,658 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-16 02:35:04,825 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:35:10,808 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-01-16 02:35:13,570 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:35:31,209 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-16 02:35:34,132 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:35:40,694 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-01-16 02:35:41,877 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:36:52,829 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-16 02:36:55,874 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:37:02,299 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-01-16 02:37:04,747 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:37:20,181 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-16 02:37:22,502 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:37:30,051 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-01-16 02:37:32,586 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:37:39,423 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2021-01-16 02:37:41,983 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:37:47,123 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2021-01-16 02:37:48,069 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 02:38:25,704 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 02:38:33,792 log 222 Not Found: /browse_histories/
WARNING 2021-01-16 02:38:33,793 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 5359
INFO 2021-01-16 02:38:33,837 basehttp 154 "GET /info/ HTTP/1.1" 200 150
INFO 2021-01-16 02:38:37,148 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
ERROR 2021-01-16 02:38:37,292 log 222 Internal Server Error: /addresses/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py", line 487, in get
    'default_address_id': user.default_address.id,
AttributeError: 'NoneType' object has no attribute 'id'
ERROR 2021-01-16 02:38:37,294 basehttp 154 "GET /addresses/ HTTP/1.1" 500 81944
INFO 2021-01-16 02:38:44,116 basehttp 154 "GET /areas/330000/ HTTP/1.1" 200 601
INFO 2021-01-16 02:38:45,440 basehttp 154 "GET /areas/330300/ HTTP/1.1" 200 601
INFO 2021-01-16 02:38:55,017 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 304
INFO 2021-01-16 02:38:56,293 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2021-01-16 02:38:56,380 basehttp 154 "GET /addresses/ HTTP/1.1" 200 333
INFO 2021-01-16 02:39:03,542 basehttp 154 "GET /areas/140000/ HTTP/1.1" 200 601
INFO 2021-01-16 02:39:04,931 basehttp 154 "GET /areas/140300/ HTTP/1.1" 200 301
INFO 2021-01-16 02:39:12,425 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 292
INFO 2021-01-16 02:39:13,489 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2021-01-16 02:39:13,644 basehttp 154 "GET /addresses/ HTTP/1.1" 200 587
INFO 2021-01-16 02:39:17,689 basehttp 154 "OPTIONS /addresses/2/default/ HTTP/1.1" 200 0
INFO 2021-01-16 02:39:17,797 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 200 27
INFO 2021-01-16 02:39:18,807 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2021-01-16 02:39:18,891 basehttp 154 "GET /addresses/ HTTP/1.1" 200 587
INFO 2021-01-16 02:39:24,924 basehttp 154 "OPTIONS /addresses/2/ HTTP/1.1" 200 0
INFO 2021-01-16 02:39:25,099 basehttp 154 "DELETE /addresses/2/ HTTP/1.1" 200 27
INFO 2021-01-16 02:39:26,639 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2021-01-16 02:39:26,708 basehttp 154 "GET /addresses/ HTTP/1.1" 200 333
INFO 2021-01-16 02:39:31,253 basehttp 154 "GET /areas/130000/ HTTP/1.1" 200 701
INFO 2021-01-16 02:39:32,337 basehttp 154 "GET /areas/130300/ HTTP/1.1" 200 459
INFO 2021-01-16 02:39:34,063 basehttp 154 "OPTIONS /addresses/1/ HTTP/1.1" 200 0
INFO 2021-01-16 02:39:34,186 basehttp 154 "PUT /addresses/1/ HTTP/1.1" 200 316
INFO 2021-01-16 02:39:46,863 basehttp 154 "OPTIONS /password/ HTTP/1.1" 200 0
INFO 2021-01-16 02:39:47,208 basehttp 154 "PUT /password/ HTTP/1.1" 200 27
INFO 2021-01-16 02:39:56,101 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2021-01-16 02:39:57,484 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:39:57,487 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
WARNING 2021-01-16 02:40:02,281 log 222 Not Found: /browse_histories/
WARNING 2021-01-16 02:40:02,282 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 5359
INFO 2021-01-16 02:40:02,335 basehttp 154 "GET /info/ HTTP/1.1" 200 150
INFO 2021-01-16 02:40:04,440 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2021-01-16 02:40:04,499 basehttp 154 "GET /addresses/ HTTP/1.1" 200 345
WARNING 2021-01-16 02:42:17,643 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:42:17,649 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
INFO 2021-01-16 02:42:31,218 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 02:42:37,640 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:42:37,643 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
INFO 2021-01-16 02:44:55,118 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 02:45:01,663 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:45:01,668 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
WARNING 2021-01-16 02:45:26,000 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:45:26,002 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
INFO 2021-01-16 02:55:11,625 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 02:55:26,911 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:55:26,915 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
INFO 2021-01-16 02:55:46,806 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2021-01-16 02:55:47,133 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2021-01-16 02:55:48,924 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 02:55:48,925 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5347
INFO 2021-01-16 03:11:06,342 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-16 03:11:09,208 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:11:20,558 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-16 03:11:23,404 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:12:50,642 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-16 03:12:54,187 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:12:59,530 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-16 03:13:00,299 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:24:39,807 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 03:24:50,733 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:24:50,740 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5501
INFO 2021-01-16 03:25:00,132 basehttp 154 "GET /search/?q=apple&page=1&page_size=6 HTTP/1.1" 200 2333
INFO 2021-01-16 03:25:12,380 basehttp 154 "GET /search/?q=huawei&page=1&page_size=6 HTTP/1.1" 200 2667
INFO 2021-01-16 03:25:58,766 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/goods/views.py changed, reloading.
INFO 2021-01-16 03:26:02,598 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:26:10,420 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/goods/views.py changed, reloading.
INFO 2021-01-16 03:26:13,594 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:26:37,046 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/goods/views.py changed, reloading.
INFO 2021-01-16 03:26:40,212 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:26:55,909 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/goods/urls.py changed, reloading.
INFO 2021-01-16 03:26:58,565 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:27:06,943 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 03:27:20,341 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:27:20,342 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5682
INFO 2021-01-16 03:27:27,057 basehttp 154 "GET /search/?q=Apple&page=1&page_size=6 HTTP/1.1" 200 2333
WARNING 2021-01-16 03:27:43,452 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:27:43,456 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5682
INFO 2021-01-16 03:27:43,456 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2021-01-16 03:27:43,478 log 222 Not Found: /browse_histories/
WARNING 2021-01-16 03:27:43,479 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5695
INFO 2021-01-16 03:28:20,417 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/goods/views.py changed, reloading.
INFO 2021-01-16 03:28:24,051 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:28:29,674 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/goods/urls.py changed, reloading.
INFO 2021-01-16 03:28:31,859 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-16 03:30:30,558 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 03:30:37,119 log 222 Not Found: /carts/simple/
ERROR 2021-01-16 03:30:37,619 log 222 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py", line 658, in post
    p.execute()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
WARNING 2021-01-16 03:30:40,520 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:30:40,521 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6021
ERROR 2021-01-16 03:30:40,667 log 222 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py", line 658, in post
    p.execute()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR 2021-01-16 03:30:40,668 basehttp 154 "POST /browse_histories/ HTTP/1.1" 500 111538
INFO 2021-01-16 03:30:43,336 basehttp 154 "GET /info/ HTTP/1.1" 200 150
ERROR 2021-01-16 03:30:43,522 log 222 Internal Server Error: /browse_histories/
Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/apps/users/views.py", line 675, in get
    sku_ids = conn.lrange('history_%s' % user.id, 0, -1)  # 从左到右
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/client.py", line 1975, in lrange
    return self.execute_command('LRANGE', name, start, end)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/yuanchu/.virtualenvs/meiduo_mall/lib/python3.9/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR 2021-01-16 03:30:43,527 basehttp 154 "GET /browse_histories/ HTTP/1.1" 500 114992
INFO 2021-01-16 03:31:10,118 autoreload 217 /Users/yuanchu/Desktop/meiduo_mall_project/meiduo_mall/meiduo_mall/settings/dev.py changed, reloading.
INFO 2021-01-16 03:31:12,981 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-16 03:31:20,547 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:31:20,547 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6021
INFO 2021-01-16 03:31:27,915 basehttp 154 "GET /search/?q=apple&page=1&page_size=6 HTTP/1.1" 200 2333
WARNING 2021-01-16 03:31:30,518 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:31:30,521 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6021
INFO 2021-01-16 03:31:30,697 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 27
WARNING 2021-01-16 03:31:35,246 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:31:35,249 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6021
INFO 2021-01-16 03:31:35,326 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 27
WARNING 2021-01-16 03:31:39,479 log 222 Not Found: /carts/simple/
WARNING 2021-01-16 03:31:39,480 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6021
INFO 2021-01-16 03:31:39,651 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 27
INFO 2021-01-16 03:31:42,419 basehttp 154 "GET /info/ HTTP/1.1" 200 150
INFO 2021-01-16 03:31:42,448 basehttp 154 "GET /browse_histories/ HTTP/1.1" 200 754
